### PR TITLE
Adds Moonfish

### PR DESCRIPTION
**Pull request by ronaldmannak**
We're currently in limited beta. 2 minute [Loom demo here](https://youtu.be/dZQwqWz9g0s). Happy to provide invites.

### CODE REVIEW

**Review by Lissy93 — COMMENTED** [review]
Heya @ronaldmannak - Thanks for your submission!
Moonfish looks super cool, I love the concept and am looking forward to trying it out.
... but I think let's wait until there's a public, and non-invite-only version released before merging.

**Comment by ronaldmannak** [comment]
Hi @Lissy93 Sounds great. Do you want me to keep the PR open or close it until we've launched?

**Comment by Lissy93** [comment]
Let's just keep it open, bit easier. But feel free to update it if any of the info changes on your end.

In the meantime, I've increased the pagnation limit (in d92bc69913b57af54d9f22b977c3f47a0dc57649) so new additions are no longer hidden on page 2,

**Comment by ronaldmannak** [comment]
Thanks for increasing the pagination limit. Being below the fold isn't great :)

**Comment by Lissy93** [comment]
Hey @ronaldmannak - how's development on Moonfish going?

**Comment by ronaldmannak** [comment]
@Lissy93 Thanks for following up. Couldn't raise money for Moonfish, so I had to abandon it unfortunately.

**Comment by Lissy93** [comment]
Ah sorry to hear that.
I've closed this PR then.

But don't let lack of funding put you off, keep working on it on the side - and if the code on GitHub is good, it naturally pick up traction :)

**Pull request closed without merging**
