### PR TITLE
Add Skiff - privacy-first, E2EE email

### PR DESCRIPTION
**Pull request by amilich**
1. Data added in `data.yml`
2. Tested via `yarn dev`

Let me know if other tests are needed.

### CODE REVIEW

**Comment by iAnonymous3000** [comment]
I have been using Skiff products for a while now. It has great UI/UX. In this case, you don't have to compromise on convenience to use a privacy-respecting tool. Features that make them stand out - completely opensource, Brave Wallet/Metamask login etc.

**Review by Lissy93 — COMMENTED** [review]
Thanks @amilich for the contribution

Skiff looks awesome, I will verify everything here and then (if all checks out) get it merged this weekend.

In the meantime, (I should have added this to the PR template), but could you confirm if your associated with the project in any way, just for transparency.

Thanks very much!

**Comment by amilich** [comment]
> Thanks @amilich for the contribution
> 
> Skiff looks awesome, I will verify everything here and then (if all checks out) get it merged this weekend.
> 
> In the meantime, (I should have added this to the PR template), but could you confirm if your associated with the project in any way, just for transparency.
> 
> Thanks very much!

Thank you!

And yes, certainly - I'm one of the creators of Skiff. I received a couple Twitter DMs/mentions in the last week to submit a PR.

**Review by Lissy93 — APPROVED** [review]
Hi @amilich 
Have tested out Skiff, and everything you've added here matches, and is definitely compatible with this list.
Thanks again for your contribution, it will be merged shortly.

**Comment by Lissy93** [comment]
Merged!
I think Skiff would also be a good fit for [Awesome-Privacy](https://github.com/Lissy93/awesome-privacy/), and that repo gets considerably more traffic than this one. Feel free to open a PR over there, and I can drop it a review :)

**Comment by amilich** [comment]
> Merged! I think Skiff would also be a good fit for [Awesome-Privacy](https://github.com/Lissy93/awesome-privacy/), and that repo gets considerably more traffic than this one. Feel free to open a PR over there, and I can drop it a review :)

Great idea! Thanks for the suggestion. I'll open up a PR now :)

**Comment by amilich** [comment]
Just created https://github.com/Lissy93/awesome-privacy/pull/101

**Pull request merged**
